### PR TITLE
E_CLASSROOM-174 [BE] Student List Page Backend Functionality [1/3]

### PR DESCRIPTION
**Pull request by CaneteJoash**
### Issue Link
https://framgiaph.backlog.com/view/E_CLASSROOM-174

### Definition of Done
- [x] User should be able to view list of students.

### Commands to Run
N/A

#### Main note
- You should add more user.
- just simple register a new account.
- be sure to put bearer token in post man.
- login user should not display in the list.
#### Pages Affected
- `http://localhost:82/api/v1/students`

#### Scenarios/ Test Cases
- [x] User should be able to view list of students.

### Screenshots
image

### CODE REVIEW

**Comment by Johnpaullim** [comment]
### Working 

- [x]  Able to view list of students.
- [x]   Functionality is working.

<details><summary>Screenshot</summary>

Jpost

jposts

Screenshot 2021-11-24 162324

</details> 


- Total Test time: 0.5 hr

**Comment by Johnpaullim** [comment]
## Approved PR #22

- [x]  Able to view list of students.
- [x]  Functionality is working.
<details><summary>Screenshot</summary>

Screenshot 2021-11-24 162324

jposts

Jpost

</details>


------
- Total Test time: 0.5 hr
- Total Comments: 2

**Comment by syntaxerron** [comment]
- [x] Use Eloquent ORM when retrieving list of students..

**Comment by syntaxerron** [comment]
- [x] Don't limit to id and name the retrieved information.

**Pull request merged**
